version: 0.2
env:
  variables:
    IMAGE_TAG: latest
    AWS_REGION: us-east-1
    ECR_REPO_NAME: my-backend-repo

phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"my-backend","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
