version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"
    DOCKERHUB_IMAGE: "yourdockerhubuser/my-backend"
    ECR_REPO: "my-backend-repo"
    AWS_REGION: "us-east-1"
    # Use environment variables or Secrets Manager if needed
    DOCKERHUB_USERNAME: "yourdockerhubuser"
    DOCKERHUB_PASSWORD: "yourpassword_or_token"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - echo Logging into Amazon ECR...
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Pulling image from Docker Hub...
      - docker pull $DOCKERHUB_IMAGE:$IMAGE_TAG

      - echo Tagging image for ECR...
      - docker tag $DOCKERHUB_IMAGE:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definition for ECS (optional)...
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
